//
// $Id$

package com.threerings.bugs.client;

import java.awt.event.ActionEvent;

import com.samskivert.swing.event.CommandEvent;

import com.threerings.crowd.client.PlaceView;
import com.threerings.crowd.data.PlaceConfig;
import com.threerings.crowd.data.PlaceObject;
import com.threerings.crowd.util.CrowdContext;

import com.threerings.parlor.game.client.GameController;

import com.threerings.bugs.data.BugPath;
import com.threerings.bugs.data.BugsObject;
import com.threerings.bugs.util.BugsContext;

import static com.threerings.bugs.Log.log;

/**
 * Handles the logic and flow of the client side of a Bugs game.
 */
public class BugsController extends GameController
{
    /** The name of the command posted by the "Back to lobby" button in
     * the side bar. */
    public static final String BACK_TO_LOBBY = "BackToLobby";

    /** A command that requests to set a path on a piece. */
    public static final String SET_PATH = "SetPath";

    // documentation inherited
    public void init (CrowdContext ctx, PlaceConfig config)
    {
        super.init(ctx, config);
        _ctx = (BugsContext)ctx;
    }

    // documentation inherited
    public void willEnterPlace (PlaceObject plobj)
    {
        super.willEnterPlace(plobj);
        _bugsobj = (BugsObject)plobj;

        // we may be returning to an already started game
        if (_bugsobj.isInPlay()) {
            _panel.view.startGame(_bugsobj);
        }
    }

    /** Handles a request to leave the game. Generated by the {@link
     * #BACK_TO_LOBBY} command. */
    public void handleBackToLobby (Object source)
    {
        _ctx.getLocationDirector().moveBack();
    }

    /** Handles a request to set a path on a piece. Generated by the
     * {@link #SET_PATH} command. */
    public void handleSetPath (Object source, BugPath path)
    {
        log.info("Requesting " + path);
        _bugsobj.service.setPath(_ctx.getClient(), path);
    }

    // documentation inherited
    protected PlaceView createPlaceView (CrowdContext ctx)
    {
        return _panel = new BugsPanel((BugsContext)ctx, this);
    }

    // documentation inherited
    protected void gameDidStart ()
    {
        super.gameDidStart();

        // we may be returning to an already started game
        _panel.view.startGame(_bugsobj);
    }

    // documentation inherited
    protected void gameWillReset ()
    {
        super.gameWillReset();
        _panel.view.endGame();
    }

    // documentation inherited
    protected void gameDidEnd ()
    {
        super.gameDidEnd();
        _panel.view.endGame();
    }

    /** A casted reference to our context. */
    protected BugsContext _ctx;

    /** Contains our main user interface. */
    protected BugsPanel _panel;

    /** A casted reference to our game object. */
    protected BugsObject _bugsobj;
}
